# -*- coding: utf-8 -*-
"""Programmers - Create strange characters

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gHt_3_InhjOyoBprsKbg5XIaIzQsEB5k

## Create strange characters

The string 's' consists of one or more words. 
Each word is separated by one or more space characters.
Complete the solution, a function that returns a string with an even letter in capital letters and an odd letter in lowercase letters.


*   You must determine the even/odd index by word (based on space), not the even/odd index of the entire string.

*   The first letter must be treated as an even number of letters, as seen by the 0 th index.


```
for example : if s = "try hello world", return "TrY HeLlO WoRlD"
```
"""

import time

start = time.time()

def solution(s):

# Solution ===========================

    answer = ''
    num = 0
    
    for alphabet in s:
        
        if alphabet == ' ' :
            num = -1

        if num % 2 == 0 :
            answer += alphabet.upper()
            num += 1
        else:
            answer += alphabet.lower()
            num += 1
      
# ====================================
    return answer

print(solution("try hello world"), end = '\n\n')

end = time.time()

print("Operation time :", f"{end - start:.5f} sec")